import Document, { Html, Head, Main, NextScript } from 'next/document'

class MyDocument extends Document {
  render() {
    return (
      <Html>
      <Head>
        <title>JJ Pisos</title>
        <meta name=" JJ PISOS | Instalação de pisos laminanos e pisos vinilicos" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </Html>
    )
  }
}

export default MyDocument